-- AlterTable
ALTER TABLE "TestModel" ADD COLUMN     "backToAnyQuestion" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "currentActiveEnd" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "currentActiveStart" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "preRegistration" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "showResultQuestion" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "showResultTest" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "startAnyTime" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "timeLimit" INTEGER NOT NULL DEFAULT 0;
